import React, { useEffect } from 'react';
import { BookOpen, FileText } from 'lucide-react';
import { EmptyState, PageHeader, StatusBadge, cardClass } from '../../components/portal/ui';
import { useAuthStore } from '../../store/authStore';
import { usePortalStore } from '../../store/portalStore';

const StudentAcademics: React.FC = () => {
  const { user } = useAuthStore();
  const { studentPortal, isLoading, error, loadStudentData } = usePortalStore();
  useEffect(() => { if (user?.id) void loadStudentData(user.id); }, [loadStudentData, user?.id]);
  const transcripts = studentPortal?.transcripts ?? [];
  return <div className="space-y-8"><PageHeader eyebrow="Academic records" title="My academics" description="Review the official transcript summaries published to your student account." />{error && <div className="rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-800">{error}</div>}{isLoading ? <div className="h-72 animate-pulse rounded-2xl bg-slate-200" /> : <><section className={`${cardClass} p-6`}><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-teal-50 text-teal-700"><BookOpen className="h-5 w-5" /></div><div><h2 className="font-semibold text-slate-950">Academic standing</h2><p className="mt-1 text-sm text-slate-500">{studentPortal?.student?.program_name || 'Programme not assigned'}</p></div></div><div className="mt-6 grid gap-4 sm:grid-cols-3"><div className="rounded-xl bg-slate-50 p-4"><p className="text-xs font-semibold uppercase tracking-wide text-slate-400">Cumulative GPA</p><p className="mt-2 text-2xl font-semibold">{transcripts[0]?.cumulative_gpa?.toFixed(2) || '—'}</p></div><div className="rounded-xl bg-slate-50 p-4"><p className="text-xs font-semibold uppercase tracking-wide text-slate-400">Credits earned</p><p className="mt-2 text-2xl font-semibold">{transcripts[0]?.credits_earned ?? '—'}</p></div><div className="rounded-xl bg-slate-50 p-4"><p className="text-xs font-semibold uppercase tracking-wide text-slate-400">Student status</p><div className="mt-3"><StatusBadge status={studentPortal?.student?.status || 'pending'} /></div></div></div></section><section className={`${cardClass} overflow-hidden`}><div className="border-b border-slate-100 px-6 py-5"><div className="flex items-center gap-2"><FileText className="h-5 w-5 text-slate-500" /><h2 className="font-semibold">Transcript summaries</h2></div></div>{transcripts.length === 0 ? <div className="p-6"><EmptyState title="No transcript published" description="Your term results will appear here once the Registrar publishes them." /></div> : <div className="overflow-x-auto"><table className="min-w-full divide-y divide-slate-100 text-left"><thead className="bg-slate-50"><tr>{['Term', 'Credits attempted', 'Credits earned', 'Term GPA', 'Cumulative GPA'].map((heading) => <th key={heading} className="px-5 py-3 text-xs font-semibold uppercase tracking-wide text-slate-500">{heading}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{transcripts.map((transcript) => <tr key={transcript.id}><td className="px-5 py-4 text-sm font-medium text-slate-900">{transcript.term_id}</td><td className="px-5 py-4 text-sm text-slate-600">{transcript.credits_attempted}</td><td className="px-5 py-4 text-sm text-slate-600">{transcript.credits_earned}</td><td className="px-5 py-4 text-sm text-slate-600">{transcript.term_gpa?.toFixed(2) || '—'}</td><td className="px-5 py-4 text-sm font-semibold text-slate-900">{transcript.cumulative_gpa?.toFixed(2) || '—'}</td></tr>)}</tbody></table></div>}</section></>}</div>;
};

export default StudentAcademics;
