import React, { useEffect } from 'react';
import { Link } from 'react-router-dom';
import { ArrowUpRight, Bell, BookOpen, CalendarDays, FileText, GraduationCap } from 'lucide-react';
import { EmptyState, PageHeader, StatCard, StatusBadge, cardClass } from '../../components/portal/ui';
import { useAuthStore } from '../../store/authStore';
import { usePortalStore } from '../../store/portalStore';

const StudentDashboard: React.FC = () => {
  const { user } = useAuthStore();
  const { studentPortal, isLoading, error, loadStudentData } = usePortalStore();
  useEffect(() => { if (user?.id) void loadStudentData(user.id); }, [loadStudentData, user?.id]);
  const student = studentPortal?.student;
  const latestTranscript = studentPortal?.transcripts[0];

  return <div className="space-y-8"><PageHeader eyebrow="Student services" title={`Welcome back, ${user?.name?.split(' ')[0] || 'student'}.`} description="Your academic journey, important updates and next actions in one calm workspace." action={<Link to="/student/profile" className="inline-flex items-center gap-2 rounded-xl border border-slate-300 bg-white px-4 py-2.5 text-sm font-semibold text-slate-700 hover:bg-slate-50">View profile <ArrowUpRight className="h-4 w-4" /></Link>} />
    {error && <div className="rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-800">{error}</div>}
    {!isLoading && !student ? <EmptyState title="Your student record is not ready yet" description="A student profile appears after an admissions application is approved. If you have already been approved, contact the Registrar." action={<Link to="/" className="font-semibold text-slate-900">Return to the public website</Link>} /> : <><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Student number" value={student?.student_number || '—'} detail={student?.status || 'Awaiting record'} icon={<GraduationCap className="h-5 w-5" />} /><StatCard label="Programme" value={student?.program_name || '—'} detail={student?.department_name || 'Department not assigned'} icon={<BookOpen className="h-5 w-5" />} tone="teal" /><StatCard label="Cumulative GPA" value={latestTranscript?.cumulative_gpa?.toFixed(2) || '—'} detail={latestTranscript ? `${latestTranscript.credits_earned} credits earned` : 'No transcript published'} icon={<FileText className="h-5 w-5" />} tone="amber" /><StatCard label="Status" value={student?.status || '—'} detail={student?.enrollment_date ? `Since ${new Date(student.enrollment_date).toLocaleDateString()}` : 'Enrollment date pending'} icon={<CalendarDays className="h-5 w-5" />} tone="rose" /></div>
      <div className="grid gap-6 xl:grid-cols-[1.3fr_1fr]"><section className={`${cardClass} p-6`}><div className="flex items-center justify-between"><div><h2 className="font-semibold text-slate-950">Your academic snapshot</h2><p className="mt-1 text-sm text-slate-500">The latest information available from the Registrar.</p></div><StatusBadge status={student?.status || 'pending'} /></div><dl className="mt-6 grid gap-5 sm:grid-cols-2"><div><dt className="text-xs font-semibold uppercase tracking-wide text-slate-400">Programme</dt><dd className="mt-1 text-sm font-medium text-slate-900">{student?.program_name || 'Not assigned'}</dd></div><div><dt className="text-xs font-semibold uppercase tracking-wide text-slate-400">Department</dt><dd className="mt-1 text-sm font-medium text-slate-900">{student?.department_name || 'Not assigned'}</dd></div><div><dt className="text-xs font-semibold uppercase tracking-wide text-slate-400">Credits earned</dt><dd className="mt-1 text-sm font-medium text-slate-900">{latestTranscript?.credits_earned ?? '—'}</dd></div><div><dt className="text-xs font-semibold uppercase tracking-wide text-slate-400">Latest term GPA</dt><dd className="mt-1 text-sm font-medium text-slate-900">{latestTranscript?.term_gpa?.toFixed(2) || '—'}</dd></div></dl></section><section className={`${cardClass} p-6`}><div className="flex items-center gap-2"><Bell className="h-5 w-5 text-teal-600" /><h2 className="font-semibold text-slate-950">Next actions</h2></div><div className="mt-5 space-y-3"><Link to="/student/profile" className="block rounded-xl border border-slate-200 p-4 hover:border-slate-950"><p className="text-sm font-semibold">Keep your profile current</p><p className="mt-1 text-xs leading-5 text-slate-500">Review your contact information before registration.</p></Link><Link to="/student/academics" className="block rounded-xl border border-slate-200 p-4 hover:border-slate-950"><p className="text-sm font-semibold">View academic records</p><p className="mt-1 text-xs leading-5 text-slate-500">Check your latest transcript and results.</p></Link></div></section></div>
      <section className="grid gap-4 md:grid-cols-3"><Link to="/student/academics" className={`${cardClass} p-5 hover:border-slate-400`}><p className="text-xs font-semibold uppercase tracking-wide text-slate-400">Current term</p><p className="mt-2 font-semibold">{studentPortal?.currentTerm?.name || 'No current term'}</p><p className="mt-1 text-sm text-slate-500">{studentPortal?.registrations.filter((registration) => registration.status !== 'dropped').length || 0} registered courses</p></Link><Link to="/student/finance" className={`${cardClass} p-5 hover:border-slate-400`}><p className="text-xs font-semibold uppercase tracking-wide text-slate-400">Financial account</p><p className="mt-2 font-semibold">{studentPortal?.invoices.length || 0} invoices</p><p className="mt-1 text-sm text-slate-500">Balance {(studentPortal?.invoices.reduce((sum, invoice) => sum + (invoice.balance || 0), 0) || 0).toFixed(2)}</p></Link><Link to="/student/documents" className={`${cardClass} p-5 hover:border-slate-400`}><p className="text-xs font-semibold uppercase tracking-wide text-slate-400">Documents</p><p className="mt-2 font-semibold">{studentPortal?.documents.length || 0} records</p><p className="mt-1 text-sm text-slate-500">View admission documents and verification status</p></Link></section>
      <section className={`${cardClass} p-6`}><div className="flex items-center justify-between"><div><h2 className="font-semibold text-slate-950">Latest announcements</h2><p className="mt-1 text-sm text-slate-500">Updates published for the university community.</p></div><Link to="/student/announcements" className="text-sm font-semibold text-slate-700">View all</Link></div><div className="mt-5 grid gap-3 md:grid-cols-2">{(studentPortal?.announcements ?? []).slice(0, 4).map((announcement) => <article key={announcement.id} className="rounded-xl border border-slate-200 p-4"><p className="text-xs font-semibold uppercase tracking-wide text-slate-400">{announcement.content_type}</p><h3 className="mt-2 text-sm font-semibold text-slate-900">{announcement.title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{announcement.summary || announcement.body}</p></article>)}{!isLoading && !(studentPortal?.announcements.length) && <div className="md:col-span-2"><EmptyState title="No announcements" description="New university updates will appear here." /></div>}</div></section></>}</div>;
};

export default StudentDashboard;
