import React, { useEffect, useMemo, useState } from 'react';
import { Plus, Save } from 'lucide-react';
import { Button, EmptyState, Input, Notice, PageHeader, Select, cardClass } from '../../components/portal/ui';
import { usePortalStore } from '../../store/portalStore';

const AdminDepartments: React.FC = () => {
  const { departments, programs, isLoading, error, loadCatalogue, addDepartment, addProgram } = usePortalStore();
  const [showDepartment, setShowDepartment] = useState(false);
  const [showProgram, setShowProgram] = useState(false);
  const [departmentForm, setDepartmentForm] = useState({ code: '', name: '', description: '' });
  const [programForm, setProgramForm] = useState({ department_id: '', code: '', name: '', degree_level: 'undergraduate', duration_years: 4, active: true });
  const [saving, setSaving] = useState(false);
  const departmentMap = useMemo(() => new Map(departments.map((department) => [department.id, department.name])), [departments]);
  useEffect(() => { void loadCatalogue(); }, [loadCatalogue]);

  const saveDepartment = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); try { await addDepartment(departmentForm); setDepartmentForm({ code: '', name: '', description: '' }); setShowDepartment(false); } finally { setSaving(false); } };
  const saveProgram = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); try { await addProgram(programForm); setProgramForm({ department_id: '', code: '', name: '', degree_level: 'undergraduate', duration_years: 4, active: true }); setShowProgram(false); } finally { setSaving(false); } };

  return <div className="space-y-8"><PageHeader eyebrow="Academic catalogue" title="Departments & programmes" description="Maintain the catalogue used by public admissions and student records." action={<div className="flex gap-2"><Button variant="secondary" onClick={() => setShowDepartment((value) => !value)}><Plus className="mr-1.5 h-4 w-4" /> Department</Button><Button onClick={() => setShowProgram((value) => !value)}><Plus className="mr-1.5 h-4 w-4" /> Programme</Button></div>} />
    {error && <Notice tone="error">{error}</Notice>}
    {(showDepartment || showProgram) && <div className="grid gap-6 lg:grid-cols-2">{showDepartment && <form onSubmit={saveDepartment} className={`${cardClass} space-y-4 p-6`}><h2 className="font-semibold">Add department</h2><Input required placeholder="Code, e.g. TECH" value={departmentForm.code} onChange={(event) => setDepartmentForm({ ...departmentForm, code: event.target.value.toUpperCase() })} /><Input required placeholder="Department name" value={departmentForm.name} onChange={(event) => setDepartmentForm({ ...departmentForm, name: event.target.value })} /><Input placeholder="Short description" value={departmentForm.description} onChange={(event) => setDepartmentForm({ ...departmentForm, description: event.target.value })} /><Button disabled={saving}><Save className="mr-1.5 h-4 w-4" /> Save department</Button></form>}{showProgram && <form onSubmit={saveProgram} className={`${cardClass} space-y-4 p-6`}><h2 className="font-semibold">Add programme</h2><Select required value={programForm.department_id} onChange={(event) => setProgramForm({ ...programForm, department_id: event.target.value })}><option value="">Select department</option>{departments.map((department) => <option key={department.id} value={department.id}>{department.name}</option>)}</Select><Input required placeholder="Code, e.g. BSC-CS" value={programForm.code} onChange={(event) => setProgramForm({ ...programForm, code: event.target.value.toUpperCase() })} /><Input required placeholder="Programme name" value={programForm.name} onChange={(event) => setProgramForm({ ...programForm, name: event.target.value })} /><Select value={programForm.degree_level} onChange={(event) => setProgramForm({ ...programForm, degree_level: event.target.value })}><option value="certificate">Certificate</option><option value="diploma">Diploma</option><option value="undergraduate">Undergraduate</option><option value="postgraduate">Postgraduate</option></Select><Input type="number" min="0.5" step="0.5" value={programForm.duration_years} onChange={(event) => setProgramForm({ ...programForm, duration_years: Number(event.target.value) })} /><Button disabled={saving}><Save className="mr-1.5 h-4 w-4" /> Save programme</Button></form>}</div>}
    <div className="grid gap-6 xl:grid-cols-2">{isLoading ? <div className={`${cardClass} h-72 animate-pulse bg-slate-100`} /> : <section className={`${cardClass} p-6`}><h2 className="font-semibold">Departments <span className="ml-1 text-sm font-normal text-slate-500">{departments.length}</span></h2><div className="mt-5 space-y-3">{departments.length === 0 ? <EmptyState title="No departments" description="Add a department to begin building the catalogue." /> : departments.map((department) => <div key={department.id} className="rounded-xl border border-slate-200 p-4"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-wide text-slate-500">{department.code}</p><p className="mt-1 font-semibold text-slate-900">{department.name}</p></div><span className="rounded-full bg-teal-50 px-2.5 py-1 text-xs font-semibold text-teal-700">{programs.filter((program) => program.department_id === department.id).length} programmes</span></div><p className="mt-2 text-sm leading-6 text-slate-500">{department.description || 'No description added.'}</p></div>)}</div></section>}
      <section className={`${cardClass} p-6`}><h2 className="font-semibold">Programmes <span className="ml-1 text-sm font-normal text-slate-500">{programs.length}</span></h2><div className="mt-5 space-y-3">{programs.length === 0 ? <EmptyState title="No programmes" description="Add programmes after creating a department." /> : programs.map((program) => <div key={program.id} className="flex items-center justify-between gap-4 rounded-xl border border-slate-200 p-4"><div><p className="text-xs font-bold uppercase tracking-wide text-slate-500">{program.code}</p><p className="mt-1 font-semibold text-slate-900">{program.name}</p><p className="mt-1 text-xs text-slate-500">{departmentMap.get(program.department_id) || 'Department'} · {program.degree_level} · {program.duration_years} years</p></div><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${program.active ? 'bg-emerald-50 text-emerald-700' : 'bg-slate-100 text-slate-600'}`}>{program.active ? 'Active' : 'Inactive'}</span></div>)}</div></section></div>
  </div>;
};

export default AdminDepartments;
