import React, { useEffect, useState } from 'react';
import { CreditCard, FilePlus2, Wallet } from 'lucide-react';
import { Button, EmptyState, Input, Notice, PageHeader, Select, StatusBadge, cardClass } from '../../components/portal/ui';
import { usePortalStore } from '../../store/portalStore';

const Finance: React.FC = () => {
  const { students, terms, invoices, isLoading, error, loadStudents, loadTerms, loadInvoices, createInvoice, recordPayment } = usePortalStore();
  const [invoiceForm, setInvoiceForm] = useState({ studentId: '', termId: '', invoiceNumber: '', amount: '', dueDate: '', description: '' });
  const [paymentForm, setPaymentForm] = useState({ invoiceId: '', amount: '', paymentMethod: 'manual', reference: '', notes: '' });
  const [notice, setNotice] = useState<string | null>(null);
  const [saving, setSaving] = useState(false);
  useEffect(() => { void Promise.all([loadStudents(), loadTerms(), loadInvoices()]); }, [loadStudents, loadTerms, loadInvoices]);

  const submitInvoice = async (event: React.FormEvent) => {
    event.preventDefault(); setSaving(true); setNotice(null);
    try { await createInvoice({ ...invoiceForm, amount: Number(invoiceForm.amount) }); setInvoiceForm({ studentId: '', termId: '', invoiceNumber: '', amount: '', dueDate: '', description: '' }); setNotice('Invoice created.'); } catch { /* store error */ } finally { setSaving(false); }
  };
  const submitPayment = async (event: React.FormEvent) => {
    event.preventDefault(); setSaving(true); setNotice(null);
    try { await recordPayment({ ...paymentForm, amount: Number(paymentForm.amount) }); setPaymentForm({ invoiceId: '', amount: '', paymentMethod: 'manual', reference: '', notes: '' }); setNotice('Payment recorded and invoice balance updated.'); } catch { /* store error */ } finally { setSaving(false); }
  };

  return <div className="space-y-8"><PageHeader eyebrow="Finance office" title="Invoices and payments" description="Create controlled student invoices, record payments and review current balances. Financial data is restricted to authorised finance and administration roles." action={<div className="flex items-center gap-2 rounded-xl bg-emerald-50 px-3 py-2 text-sm font-semibold text-emerald-800"><Wallet className="h-4 w-4" /> {invoices.length} invoices</div>} />
    {notice && <Notice tone="success">{notice}</Notice>}{error && <Notice tone="error">{error}</Notice>}
    <div className="grid gap-6 xl:grid-cols-2"><section className={`${cardClass} p-6`}><div className="flex items-center gap-2"><FilePlus2 className="h-5 w-5 text-teal-600" /><h2 className="font-semibold">Create invoice</h2></div><form onSubmit={submitInvoice} className="mt-5 grid gap-4"><label className="text-sm font-medium">Student<Select required value={invoiceForm.studentId} onChange={(event) => setInvoiceForm({ ...invoiceForm, studentId: event.target.value })} className="mt-1.5"><option value="">Select student</option>{students.map((student) => <option key={student.id} value={student.id}>{student.student_number} · {student.name}</option>)}</Select></label><label className="text-sm font-medium">Academic term<Select required value={invoiceForm.termId} onChange={(event) => setInvoiceForm({ ...invoiceForm, termId: event.target.value })} className="mt-1.5"><option value="">Select term</option>{terms.map((term) => <option key={term.id} value={term.id}>{term.name}</option>)}</Select></label><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Invoice number<Input required value={invoiceForm.invoiceNumber} onChange={(event) => setInvoiceForm({ ...invoiceForm, invoiceNumber: event.target.value })} placeholder="INV-2026-0001" className="mt-1.5" /></label><label className="text-sm font-medium">Amount<Input required type="number" min="0" step="0.01" value={invoiceForm.amount} onChange={(event) => setInvoiceForm({ ...invoiceForm, amount: event.target.value })} className="mt-1.5" /></label></div><label className="text-sm font-medium">Due date<Input required type="date" value={invoiceForm.dueDate} onChange={(event) => setInvoiceForm({ ...invoiceForm, dueDate: event.target.value })} className="mt-1.5" /></label><label className="text-sm font-medium">Description<Input value={invoiceForm.description} onChange={(event) => setInvoiceForm({ ...invoiceForm, description: event.target.value })} placeholder="Tuition, registration or other charge" className="mt-1.5" /></label><Button type="submit" disabled={saving}><FilePlus2 className="mr-2 h-4 w-4" /> Create invoice</Button></form></section>
      <section className={`${cardClass} p-6`}><div className="flex items-center gap-2"><CreditCard className="h-5 w-5 text-teal-600" /><h2 className="font-semibold">Record payment</h2></div><form onSubmit={submitPayment} className="mt-5 grid gap-4"><label className="text-sm font-medium">Invoice<Select required value={paymentForm.invoiceId} onChange={(event) => setPaymentForm({ ...paymentForm, invoiceId: event.target.value })} className="mt-1.5"><option value="">Select invoice</option>{invoices.filter((invoice) => (invoice.balance || 0) > 0).map((invoice) => <option key={invoice.id} value={invoice.id}>{invoice.invoice_number} · {invoice.student_name} · balance {(invoice.balance || 0).toFixed(2)}</option>)}</Select></label><label className="text-sm font-medium">Amount<Input required type="number" min="0.01" step="0.01" value={paymentForm.amount} onChange={(event) => setPaymentForm({ ...paymentForm, amount: event.target.value })} className="mt-1.5" /></label><label className="text-sm font-medium">Payment method<Select value={paymentForm.paymentMethod} onChange={(event) => setPaymentForm({ ...paymentForm, paymentMethod: event.target.value })} className="mt-1.5"><option value="manual">Manual</option><option value="bank_transfer">Bank transfer</option><option value="cash">Cash</option><option value="card">Card</option><option value="mobile_money">Mobile money</option></Select></label><label className="text-sm font-medium">Reference<Input value={paymentForm.reference} onChange={(event) => setPaymentForm({ ...paymentForm, reference: event.target.value })} className="mt-1.5" /></label><label className="text-sm font-medium">Notes<Input value={paymentForm.notes} onChange={(event) => setPaymentForm({ ...paymentForm, notes: event.target.value })} className="mt-1.5" /></label><Button type="submit" disabled={saving}><CreditCard className="mr-2 h-4 w-4" /> Record payment</Button></form></section></div>
    <section className={`${cardClass} overflow-hidden`}><div className="border-b border-slate-100 p-6"><h2 className="font-semibold">Invoice register</h2><p className="mt-1 text-sm text-slate-500">The register is sourced from production records; no sample rows are created.</p></div>{isLoading ? <div className="h-48 animate-pulse bg-slate-100" /> : invoices.length === 0 ? <div className="p-6"><EmptyState title="No invoices yet" description="Create the first invoice when a real student charge is due." /></div> : <div className="overflow-x-auto"><table className="min-w-full divide-y divide-slate-100 text-left"><thead className="bg-slate-50"><tr>{['Invoice', 'Student', 'Term', 'Amount', 'Paid', 'Balance', 'Status'].map((heading) => <th key={heading} className="px-5 py-3 text-xs font-semibold uppercase tracking-wide text-slate-500">{heading}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{invoices.map((invoice) => <tr key={invoice.id}><td className="px-5 py-4 text-sm font-semibold">{invoice.invoice_number}<p className="mt-1 text-xs font-normal text-slate-500">{invoice.description || '—'}</p></td><td className="px-5 py-4 text-sm">{invoice.student_name}<p className="mt-1 text-xs text-slate-500">{invoice.student_number}</p></td><td className="px-5 py-4 text-sm text-slate-600">{invoice.term_name || '—'}</td><td className="px-5 py-4 text-sm">{invoice.amount.toFixed(2)}</td><td className="px-5 py-4 text-sm text-emerald-700">{(invoice.paid_amount || 0).toFixed(2)}</td><td className="px-5 py-4 text-sm font-semibold">{(invoice.balance || 0).toFixed(2)}</td><td className="px-5 py-4"><StatusBadge status={invoice.status} /></td></tr>)}</tbody></table></div>}</section>
  </div>;
};
export default Finance;
